sudo: false
language: node_js
node_js: 12
cache:
  apt: true
  directories:
    - node_modules

branches:
  only:
    - master # build master branch only
before_script:
  - npm install hexo-cli -g
script:
  - hexo clean # generate static files
  - hexo generate

after_success:
  - sed -i'' "/^ *repo/s~github\.com~${GH_TOKEN}@github.com~" _config.yml
  - hexo deploy
